service: challenge-autopilot
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: "*"
  environment:
    CHALLENGES_TABLE: ${env:CHALLENGES_TABLE}
    SUBMISSION_REVIEWS_TABLE: ${env:SUBMISSION_REVIEWS_TABLE}
    SUBMISSIONS_TABLE: ${env:SUBMISSIONS_TABLE}
    AUTH0_URL: ${env:AUTH0_URL}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
    TOKEN_CACHE_TIME: ${env:TOKEN_CACHE_TIME}
    AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
    AUTH0_CLIENT_SECRET: ${env:AUTH0_CLIENT_SECRET}
    MEMBERS_API_URL: ${env:MEMBERS_API_URL}
    SCHEDULE_API_URL: ${env:SCHEDULE_API_URL}
    CHALLENGE_API_URL: ${env:CHALLENGE_API_URL}
    SUBMISSIONS_API_URL: ${env:SUBMISSIONS_API_URL}
    CHALLENGE_TABLE_ARN: ${env:CHALLENGE_TABLE_ARN}
    SUBMISSION_REVIEW_TABLE_ARN: ${env:SUBMISSION_REVIEW_TABLE_ARN}
    SUBMISSIONS_TABLE_ARN: ${env:SUBMISSIONS_TABLE_ARN}
    SUBMISSION_REVIEW_SUMMATION_TABLE_ARN: ${env:SUBMISSION_REVIEW_SUMMATION_TABLE_ARN}
    RESOURCE_TABLE_STREAM_ARN: ${env:RESOURCE_TABLE_STREAM_ARN}

package:
  individually: true

useDotenv: true
plugins:
  - serverless-iam-roles-per-function
  - serverless-bundle

functions:
  # EventBridge handler functions
  schedulePhasesByChallenge:
    handler: handlers/events/schedule-phases.handlerChallenge
    events:
      - stream:
        type: dynamodb
        arn: ${env:CHALLENGE_TABLE_ARN}
  schedulePhasesByReview:
    handler: handlers/events/schedule-phases.handlerReview
    events:
      - stream:
        type: dynamodb
        arn: ${env:SUBMISSION_REVIEW_TABLE_ARN}
  schedulePhasesBySubmission:
    handler: handlers/events/schedule-phases.handlerSubmission
    events:
      - stream:
        type: dynamodb
        arn: ${env:SUBMISSIONS_TABLE_ARN}
  handleChallengeResource:
    handler: handlers/events/handle-registrants.registrantsHandler
    events:
      - stream:
          type: dynamodb
          arn: ${env:RESOURCE_TABLE_STREAM_ARN}
